export default {
  $primaryFont: 'VarelaRound-Regular',
  $secondaryFont: 'HelveticaNeue',
  $secondaryBoldFont: 'HelveticaNeue-Bold',
  $secondaryBoldItalicFont: 'HelveticaNeue-BoldItalic',
  $secondaryCondensedBlackFont: 'HelveticaNeue-CondensedBlack',
  $secondaryCondensedBoldFont: 'HelveticaNeue-CondensedBold',
  $secondaryItalicFont: 'HelveticaNeue-Italic',
  $secondaryLightFont: 'HelveticaNeue-Light',
  $secondaryLightItalicFont: 'HelveticaNeue-LightItalic',
  $secondaryMediumFont: 'HelveticaNeue-Medium',
  $secondaryUltraLightFont: 'HelveticaNeue-UltraLight',
  $secondaryUltraLightItalicFont: 'HelveticaNeue-UltraLightItalic',
  $normal: '1rem',
};
